---
:api_key: e200803e8965b88c13ffc25f3ffcdfbd
:password: e4e46fac0aea60fe3e4bde8aadf45603
:theme_id: '15'
:preview_url: https://lojapepre.commercesuite.com.br/loja/loja.php?loja=682325&opencode_theme=5c89a5e9626d7
